-- MySQL Script generated by MySQL Workbench
-- Thu Jun 14 21:15:06 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Finaceiro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Finaceiro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Finaceiro` DEFAULT CHARACTER SET utf8 ;
USE `Finaceiro` ;

-- -----------------------------------------------------
-- Table `Finaceiro`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Finaceiro`.`usuario` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Telefone` BIGINT(14) NULL,
  `Senha` VARCHAR(250) NOT NULL,
  `Data_Nascimento` DATE NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Finaceiro`.`conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Finaceiro`.`conta` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Saldo` DECIMAL(9,2) NOT NULL,
  `usuario_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_conta_usuario_idx` (`usuario_Id` ASC),
  CONSTRAINT `fk_conta_usuario`
    FOREIGN KEY (`usuario_Id`)
    REFERENCES `Finaceiro`.`usuario` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Finaceiro`.`plano_contas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Finaceiro`.`plano_contas` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(45) NOT NULL,
  `Tipo` CHAR(1) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Finaceiro`.`transacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Finaceiro`.`transacao` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Data` DATETIME NOT NULL,
  `Tipo` CHAR(1) NOT NULL,
  `Valor` DECIMAL(9,2) NOT NULL,
  `Descricao` VARCHAR(45) NULL,
  `conta_Id` INT NOT NULL,
  `plano_contas_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_transacao_conta1_idx` (`conta_Id` ASC),
  INDEX `fk_transacao_plano_contas1_idx` (`plano_contas_Id` ASC),
  CONSTRAINT `fk_transacao_conta1`
    FOREIGN KEY (`conta_Id`)
    REFERENCES `Finaceiro`.`conta` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transacao_plano_contas1`
    FOREIGN KEY (`plano_contas_Id`)
    REFERENCES `Finaceiro`.`plano_contas` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
